
COMMIT ?= $(shell git rev-parse --short HEAD)
AGENTNAME ?= "lunar_collector"

.PHONY: ${AGENTNAME} ${AGENTNAME}_arm all

LD_FLAGS := ""

all: ${AGENTNAME} ${AGENTNAME}_arm

${AGENTNAME}:
	env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ${AGENTNAME}_x86 -a  -ldflags=${LD_FLAGS}  main.go

${AGENTNAME}_arm:
	env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ${AGENTNAME}_arm64 -a  -ldflags=${LD_FLAGS}  main.go

${AGENTNAME}_local:
	CGO_ENABLED=0 go build -o ${AGENTNAME} -a  -ldflags=${LD_FLAGS}  main.go

clean:
	rm -f ${AGENTNAME}
