name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      IMAGE_NAME: cloudrec/cloudrec
      
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,enable=true,priority=600,prefix=,suffix=,event=tag
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
